language: node_js
node_js:
- "4"
deploy:
  provider: releases
  api_key:
    secure: BtPZcCuIxbEcSd+8y4DV2oQDDXlWYOWv8Fe+vkQVyuTLAWabYJPc3WCfJnma+q10W6x7rxfIJGi1EaLMkqrUKkQaJxZNscPnFy+0qLwCuBnVPrJZk1Acj82/3QShtCwMFmOG3nOIEb3As0+lHwpiXeQX2KFM49pxQtHp4bcW/VA=
  file:
    - "dist/index.js"
    - "dist/index.js.map"
  skip_cleanup: true
  on:
    repo: MiguelCastillo/pulling-deps
    tags: true
